name: Ridesystems module post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint src tests
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 src tests
      - name: Look for security issues with Bandit
        run: |
          bandit src tests
      - name: Type checking
        run: |
          mypy src tests
      - name: Testing
        run: |
          tox -vv --username ${{ secrets.RIDESYSTEMS_USERNAME }} --password ${{ secrets.RIDESYSTEMS_PASSWORD }}
