name: Ridesystems module post commit steps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip pylint flake8 bandit mypy wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint src tests
      - name: Lint with flake8
        run : |
          flake8 --config=.flake8 src tests
      - name: Look for security issues with Bandit
        run: |
          bandit src tests
      - name: Type checking
        run: |
          mypy src
      - name: Pytest
        run: |
          pytest -vv --username { secrets.RIDESYSTEMS_USERNAME } --password { secrets.RIDESYSTEMS_PASSWORD }
